[package]
name = "scrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
encoding_rs = "0.8.35"
reqwest = "0.12.9"
reqwest_cookie_store = "0.8.0"
scraper = "0.21.0"
tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros"] }
